name: 'Restrict file changes'
description: 'Prevent file changes based on a regex'
author: 'klismannsm'

# TODO
branding:
  icon: 'heart'
  color: 'green'

inputs:
  regex:
    description: Regex to match the changed files paths (Javascript format)
    required: true
  allowNewFiles:
    description: Allow new files to be added
    required: false
    default: false
  allowRemovedFiles:
    description: Allow files to be removed
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js
