name: 'Restrict file changes'
description: 'Prevent file changes based on a regex'
author: 'klismannsm'

# TODO
branding:
  icon: 'heart'
  color: 'green'

inputs:
  githubToken:
    description: Github Token to authenticate the github API
    required: true
  regex:
    description: Regex to match the changed files paths (Javascript format)
    required: true
  allowAddedFiles:
    description: Allow new files to be added
    required: false
    default: false
  allowRemovedFiles:
    description: Allow files to be removed
    required: false
    default: false
  allowAdditions:
    description: Allow content to be added
    required: false
    default: false
  allowDeletions:
    description: Allow content to be removed
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js
