name: Test action

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  test-action:
    name: Test action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          regex: tmp\/.*
